using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Simplification;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlexibleTesting.Tasks;

public class FlexibleTestingCodeGenerator
{
    private readonly Solution _solution;
    private readonly string _outputPath;
    private readonly IFlexibleTestingNamePolicy _namePolicy;
    private readonly IDependencyInterfaceGenerator _dependencyInterfaceGenerator;
    private readonly IBaseInheritanceGenerator _baseInheritanceGenerator;
    private readonly HashSet<string> _requiredNamespaces = new(StringComparer.Ordinal);

    public FlexibleTestingCodeGenerator(Solution solution, string outputPath)
        : this(
            solution,
            outputPath,
            new FlexibleTestingNamePolicy(),
            new WellKnownDelegateTypeResolver()
        )
    {
    }

    internal FlexibleTestingCodeGenerator(
        Solution solution,
        string outputPath,
        IFlexibleTestingNamePolicy namePolicy,
        IWellKnownDelegateTypeResolver delegateTypeResolver
    )
    {
        _solution = solution;
        _outputPath = outputPath;
        _namePolicy = namePolicy;
        _requiredNamespaces.Add(FlexibleTestingGeneratedNames.SystemNamespaceName);
        var syntaxFactory = new FlexibleTestingSyntaxFactory(delegateTypeResolver, namespaceName => _requiredNamespaces.Add(namespaceName));
        _dependencyInterfaceGenerator = new DependencyInterfaceGenerator(syntaxFactory, _namePolicy);
        _baseInheritanceGenerator = new BaseInheritanceGenerator(syntaxFactory, _namePolicy);
    }

    public void Generate(FlexibleTestingInstructions instructions)
    {
        var targetClassSyntax = instructions.TargetType.DeclaringSyntaxReferences[0].GetSyntax() as ClassDeclarationSyntax;
        if (targetClassSyntax == null)
            return;

        var targetDocument = instructions.TargetDocument ?? _solution.GetDocument(targetClassSyntax.SyntaxTree);
        if (targetDocument == null)
            return;

        var rewrittenDocument = ApplyRewritesAsync(targetDocument, targetClassSyntax, instructions).GetAwaiter().GetResult();
        var rewrittenRoot = rewrittenDocument.GetSyntaxRootAsync().GetAwaiter().GetResult();
        var generatedCode = rewrittenRoot!.NormalizeWhitespace(elasticTrivia: true).ToFullString();

        Directory.CreateDirectory(_outputPath);
        var generatedFilePath = Path.Combine(_outputPath, $"{_namePolicy.GetGeneratedClassName(instructions.OldClassName)}.g.cs");
        File.WriteAllText(generatedFilePath, $"// <auto-generated/>{Environment.NewLine}{generatedCode}", Encoding.UTF8);
    }

    private async Task<Document> ApplyRewritesAsync(
        Document document,
        ClassDeclarationSyntax targetClassSyntax,
        FlexibleTestingInstructions instructions
    )
    {
        _requiredNamespaces.Clear();
        _requiredNamespaces.Add(FlexibleTestingGeneratedNames.SystemNamespaceName);
        foreach (var ancestorType in instructions.RecursiveBaseTypes)
        {
            var ancestorNamespace = ancestorType.ContainingNamespace;
            if (ancestorNamespace is { IsGlobalNamespace: false })
                _requiredNamespaces.Add(ancestorNamespace.ToDisplayString());
        }

        var syntaxRoot = await document.GetSyntaxRootAsync() ?? throw new InvalidOperationException("Could not get syntax root");
        var semanticModel = await document.GetSemanticModelAsync() ?? throw new InvalidOperationException("Could not get semantic model");
        var syntaxGenerator = SyntaxGenerator.GetGenerator(document);

        var rewriter = new FlexibleTestingRewriter(semanticModel, instructions, syntaxGenerator);
        var rewrittenRoot = rewriter.Visit(syntaxRoot);

        var syntaxEditor = new SyntaxEditor(rewrittenRoot, document.Project.Solution.Workspace.Services);
        var generatedClassSyntax = rewrittenRoot
            .DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .First(classNode => classNode.Identifier.Text == instructions.NewClassName);

        AddStructuralMembers(
            syntaxEditor,
            generatedClassSyntax,
            targetClassSyntax,
            instructions,
            syntaxGenerator,
            semanticModel.Compilation
        );

        if (instructions.MockInheritance && targetClassSyntax.BaseList != null && targetClassSyntax.BaseList.Types.Any())
            _baseInheritanceGenerator.TryAddBaseInheritanceMembers(syntaxEditor, generatedClassSyntax, instructions, semanticModel, syntaxGenerator);

        var changedRoot = syntaxEditor.GetChangedRoot();
        changedRoot = AddMissingUsings(changedRoot, _requiredNamespaces, syntaxGenerator);

        var annotatedRoot = changedRoot.WithAdditionalAnnotations(Simplifier.Annotation);
        return await Simplifier.ReduceAsync(document.WithSyntaxRoot(annotatedRoot));
    }

    private void AddStructuralMembers(
        SyntaxEditor syntaxEditor,
        ClassDeclarationSyntax generatedClassSyntax,
        ClassDeclarationSyntax sourceClassSyntax,
        FlexibleTestingInstructions instructions,
        SyntaxGenerator syntaxGenerator,
        Compilation compilation
    )
    {
        var hasPrimaryConstructor = sourceClassSyntax.ParameterList != null && !sourceClassSyntax.Members.OfType<ConstructorDeclarationSyntax>().Any();
        MemberDeclarationSyntax dependenciesField;

        if (hasPrimaryConstructor)
        {
            dependenciesField = (FieldDeclarationSyntax)Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FieldDeclaration(
                Microsoft.CodeAnalysis.CSharp.SyntaxFactory.VariableDeclaration(
                    (TypeSyntax)syntaxGenerator.IdentifierName(instructions.DependenciesInterfaceName),
                    Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList(
                        new[]
                        {
                            Microsoft.CodeAnalysis.CSharp.SyntaxFactory.VariableDeclarator(
                                Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Identifier(_namePolicy.DependenciesFieldName),
                                default,
                                Microsoft.CodeAnalysis.CSharp.SyntaxFactory.EqualsValueClause(
                                    Microsoft.CodeAnalysis.CSharp.SyntaxFactory.IdentifierName(instructions.DependenciesParameterName)
                                )
                            ),
                        }
                    )
                )
            )
            .WithModifiers(
                Microsoft.CodeAnalysis.CSharp.SyntaxFactory.TokenList(
                    Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Token(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PrivateKeyword),
                    Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Token(Microsoft.CodeAnalysis.CSharp.SyntaxKind.ReadOnlyKeyword)
                )
            );
        }
        else
        {
            dependenciesField = (MemberDeclarationSyntax)syntaxGenerator.FieldDeclaration(
                _namePolicy.DependenciesFieldName,
                syntaxGenerator.IdentifierName(instructions.DependenciesInterfaceName),
                Accessibility.Private,
                DeclarationModifiers.ReadOnly
            );
        }

        syntaxEditor.AddMember(
            generatedClassSyntax,
            dependenciesField
        );

        if (instructions.MockInheritance)
        {
            syntaxEditor.AddMember(
                generatedClassSyntax,
                syntaxGenerator.FieldDeclaration(
                    _namePolicy.BaseDependenciesFieldName,
                    syntaxGenerator.IdentifierName(_namePolicy.GetBaseDependenciesInterfaceName(instructions.OldClassName)),
                    Accessibility.Private,
                    DeclarationModifiers.ReadOnly
                )
            );
        }

        var dependencyInterfaceMembers = new List<SyntaxNode>
        {
            _dependencyInterfaceGenerator.BuildDependenciesInterface(syntaxGenerator, instructions, compilation),
        };

        dependencyInterfaceMembers.AddRange(
            instructions.MockClasses
                .OrderBy(mockedTypeSymbol => mockedTypeSymbol.Name, StringComparer.Ordinal)
                .Select(mockedTypeSymbol => _dependencyInterfaceGenerator.BuildMockClassInterface(syntaxGenerator, mockedTypeSymbol))
        );

        syntaxEditor.InsertAfter(generatedClassSyntax, dependencyInterfaceMembers);
    }

    private SyntaxNode AddMissingUsings(SyntaxNode root, IEnumerable<string> namespaces, SyntaxGenerator syntaxGenerator)
    {
        if (root is not CompilationUnitSyntax compilationUnitSyntax)
            return root;

        var existingNamespaceNames = compilationUnitSyntax.Usings.Select(usingDirective => usingDirective.Name?.ToString()).ToHashSet(StringComparer.Ordinal);
        return compilationUnitSyntax.AddUsings(
            namespaces
                .Where(namespaceName => !existingNamespaceNames.Contains(namespaceName))
                .Select(namespaceName => (UsingDirectiveSyntax)syntaxGenerator.NamespaceImportDeclaration(namespaceName))
                .ToArray()
        );
    }
}
