using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Simplification;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlexibleTesting.Tasks;

public class FlexibleTestingCodeGenerator
{
    private readonly Project _legacyProject;
    private readonly string? _outputPath;

    public FlexibleTestingCodeGenerator(Project legacyProject, string? outputPath)
    {
        _legacyProject = legacyProject;
        _outputPath = outputPath;
    }

    public void Generate(FlexibleTestingInstructions instructions)
    {
        var targetSyntax = instructions.TargetType.DeclaringSyntaxReferences[0].GetSyntax() as ClassDeclarationSyntax;
        if (targetSyntax == null) return;

        var document = _legacyProject.GetDocument(targetSyntax.SyntaxTree);
        if (document == null) return;

        var rewrittenDocument = ApplyRewritesAsync(document, targetSyntax, instructions).GetAwaiter().GetResult();
        var finalRoot = rewrittenDocument.GetSyntaxRootAsync().GetAwaiter().GetResult();
        var finalCode = finalRoot!.NormalizeWhitespace(elasticTrivia: true).ToFullString();

        if (!string.IsNullOrWhiteSpace(_outputPath))
        {
            Directory.CreateDirectory(_outputPath);
            var filePath = Path.Combine(_outputPath, $"{instructions.OldClassName}_G.g.cs");
            File.WriteAllText(filePath, $"// <auto-generated/>\n{finalCode}", Encoding.UTF8);
        }
    }

    private async Task<Document> ApplyRewritesAsync(Document document, ClassDeclarationSyntax classNode, FlexibleTestingInstructions instructions)
    {
        var root = await document.GetSyntaxRootAsync() ?? throw new InvalidOperationException("Could not get syntax root");
        var model = await document.GetSemanticModelAsync() ?? throw new InvalidOperationException("Could not get semantic model");
        var generator = SyntaxGenerator.GetGenerator(document);

        var rewriter = new FlexibleTestingRewriter(model, instructions, generator);
        var transformedRoot = rewriter.Visit(root);

        var editor = new SyntaxEditor(transformedRoot, document.Project.Solution.Workspace);
        var transformedClass = transformedRoot.DescendantNodes().OfType<ClassDeclarationSyntax>().First(c => c.Identifier.Text == instructions.NewClassName);

        AddStructuralMembers(editor, transformedClass, instructions, generator, model.Compilation);

        bool baseClassNeedsCaller = false;
        if (instructions.MockInheritance && classNode.BaseList != null && classNode.BaseList.Types.Any())
        {
            baseClassNeedsCaller = AddBaseClassReplacement(editor, transformedClass, instructions, generator, model);
        }

        var finalRoot = editor.GetChangedRoot();
        var usings = new List<string> { "System" };
        if (rewriter.NeedsCallerMemberName || baseClassNeedsCaller) usings.Add("System.Runtime.CompilerServices");

        finalRoot = AddMissingUsings(finalRoot, usings, generator);
        return await Simplifier.ReduceAsync(document.WithSyntaxRoot(finalRoot));
    }

    private void AddStructuralMembers(SyntaxEditor editor, ClassDeclarationSyntax classNode, FlexibleTestingInstructions instructions, SyntaxGenerator gen, Compilation comp)
    {
        editor.AddMember(classNode, gen.FieldDeclaration(instructions.DependenciesFieldName, gen.IdentifierName(instructions.DependenciesInterfaceName), Accessibility.Private, DeclarationModifiers.ReadOnly));
        
        if (instructions.MockInheritance)
        {
            editor.AddMember(classNode, gen.FieldDeclaration("_baseDependencies", gen.IdentifierName($"IAuto{instructions.OldClassName}BaseDependencies"), Accessibility.Private, DeclarationModifiers.ReadOnly));
        }

        editor.InsertAfter(classNode, BuildDependenciesInterface(gen, instructions, comp));
    }

    private bool AddBaseClassReplacement(SyntaxEditor editor, ClassDeclarationSyntax classNode, FlexibleTestingInstructions instructions, SyntaxGenerator gen, SemanticModel model)
    {
        var baseType = instructions.TargetType.BaseType;
        if (baseType == null || baseType.SpecialType == SpecialType.System_Object) return false;

        var usedMembers = ExtractUsedBaseMembers((ClassDeclarationSyntax)instructions.TargetType.DeclaringSyntaxReferences[0].GetSyntax(), instructions.TargetType, model);
        if (!usedMembers.Any()) return false;

        var baseDepsInterfaceName = $"IAuto{instructions.OldClassName}BaseDependencies";
        editor.InsertBefore(classNode, BuildBaseClassReplacement(gen, instructions.OldClassName, baseType, usedMembers, baseDepsInterfaceName, instructions.MethodsToMakePublic));
        editor.InsertBefore(classNode, BuildBaseDependenciesInterface(gen, instructions.OldClassName, usedMembers));

        return usedMembers.OfType<IMethodSymbol>().Any(m => m.Parameters.Any(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "CallerMemberNameAttribute")));
    }

    private SyntaxNode BuildDependenciesInterface(SyntaxGenerator gen, FlexibleTestingInstructions instructions, Compilation comp)
    {
        var members = instructions.AllMockables.Select(mockable =>
        {
            var name = instructions.DependencyMemberNames[mockable];
            if (mockable is IMethodSymbol method)
            {
                var parameters = method.Parameters.Select(p =>
                {
                    var decl = gen.ParameterDeclaration(p.Name, gen.TypeExpression(p.Type));
                    if (p.GetAttributes().Any(a => a.AttributeClass?.Name == "CallerMemberNameAttribute"))
                        decl = gen.AddAttributes(decl, gen.Attribute("CallerMemberName"));
                    if (p.HasExplicitDefaultValue)
                        decl = ((ParameterSyntax)decl).WithDefault(SyntaxFactory.EqualsValueClause((ExpressionSyntax)gen.LiteralExpression(p.ExplicitDefaultValue)));
                    return decl;
                });
                return gen.MethodDeclaration(name, parameters: parameters, returnType: gen.TypeExpression(method.ReturnType), accessibility: Accessibility.Public);
            }
            return gen.PropertyDeclaration(name, gen.TypeExpression(GetMockableDelegateType(comp, mockable)), accessibility: Accessibility.Public);
        });

        return gen.InterfaceDeclaration(instructions.DependenciesInterfaceName, accessibility: Accessibility.Public, members: members)
            .WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Comment("/// <summary>Mock this using NSubstitute</summary>")));
    }

    private ITypeSymbol GetMockableDelegateType(Compilation comp, ISymbol symbol)
    {
        var (returnType, parameters) = symbol switch
        {
            IPropertySymbol p => (p.Type, Array.Empty<IParameterSymbol>()),
            IFieldSymbol f => (f.Type, Array.Empty<IParameterSymbol>()),
            IMethodSymbol m => (m.ReturnType, m.Parameters.ToArray()),
            _ => throw new ArgumentException("Unsupported symbol kind")
        };

        var isVoid = returnType.SpecialType == SpecialType.System_Void;
        var typeArgs = isVoid ? parameters.Select(p => p.Type).ToArray() : parameters.Select(p => p.Type).Append(returnType).ToArray();
        var baseName = isVoid ? "System.Action" : "System.Func";
        var metadataName = (isVoid && typeArgs.Length == 0) ? baseName : $"{baseName}`{typeArgs.Length}";
        
        var delegateSymbol = comp.GetTypeByMetadataName(metadataName) ?? throw new InvalidOperationException($"Could not find {metadataName}");
        return typeArgs.Length == 0 ? delegateSymbol : delegateSymbol.Construct(typeArgs);
    }

    private SyntaxNode BuildBaseClassReplacement(SyntaxGenerator gen, string oldName, INamedTypeSymbol baseType, List<ISymbol> usedMembers, string baseDepsInterfaceName, HashSet<IMethodSymbol> publicMethods)
    {
        var className = $"{oldName}Base_G";
        var members = new List<MemberDeclarationSyntax>();

        var ctorPars = new[] {
            gen.ParameterDeclaration("someDataObject", gen.IdentifierName(baseType.Constructors.FirstOrDefault()?.Parameters.FirstOrDefault()?.Type.Name ?? "SomeDataObject")),
            gen.ParameterDeclaration("baseDependencies", gen.IdentifierName(baseDepsInterfaceName))
        };
        var ctor = (ConstructorDeclarationSyntax)gen.ConstructorDeclaration(className, parameters: ctorPars, accessibility: Accessibility.Public);
        members.Add(ctor.WithBody(SyntaxFactory.Block(SyntaxFactory.ParseStatement("_baseDependencies = baseDependencies;"))));

        members.Add((FieldDeclarationSyntax)gen.FieldDeclaration("_baseDependencies", gen.IdentifierName(baseDepsInterfaceName), Accessibility.Private, DeclarationModifiers.ReadOnly));

        foreach (var member in usedMembers)
        {
            if (member is IMethodSymbol ms && ms.MethodKind != MethodKind.Constructor)
                members.Add(CreateBaseMethodStub(gen, ms, publicMethods.Contains(ms)));
            else if (member is IPropertySymbol ps)
                members.Add(CreateBasePropertyStub(gen, ps));
        }

        return gen.ClassDeclaration(className, accessibility: Accessibility.Public, members: members);
    }

    private MethodDeclarationSyntax CreateBaseMethodStub(SyntaxGenerator gen, IMethodSymbol ms, bool shouldBePublic)
    {
        var parameters = ms.Parameters.Select(p =>
        {
            var decl = (ParameterSyntax)gen.ParameterDeclaration(p.Name, GetTypeNameSyntax(p.Type));
            if (p.GetAttributes().Any(a => a.AttributeClass?.Name == "CallerMemberNameAttribute"))
                decl = gen.AddAttributes(decl, gen.Attribute("CallerMemberName")) as ParameterSyntax ?? decl;
            if (p.HasExplicitDefaultValue)
                decl = decl.WithDefault(SyntaxFactory.EqualsValueClause(p.ExplicitDefaultValue == null ? SyntaxFactory.LiteralExpression(SyntaxKind.NullLiteralExpression) : (ExpressionSyntax)gen.LiteralExpression(p.ExplicitDefaultValue)));
            return decl;
        });

        var callArgs = ms.Parameters.Select(p => SyntaxFactory.Argument(SyntaxFactory.IdentifierName(p.Name)));
        var invocation = SyntaxFactory.InvocationExpression(SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, SyntaxFactory.IdentifierName("_baseDependencies"), SyntaxFactory.IdentifierName(ms.Name)), SyntaxFactory.ArgumentList(SyntaxFactory.SeparatedList(callArgs)));
        var body = ms.ReturnType.SpecialType == SpecialType.System_Void ? (StatementSyntax)SyntaxFactory.ExpressionStatement(invocation) : SyntaxFactory.ReturnStatement(invocation);

        var accessibility = shouldBePublic ? Accessibility.Public : (ms.DeclaredAccessibility == Accessibility.Protected ? Accessibility.Protected : Accessibility.Public);
        return ((MethodDeclarationSyntax)gen.MethodDeclaration(ms.Name, parameters: parameters, returnType: GetTypeNameSyntax(ms.ReturnType), accessibility: accessibility, modifiers: DeclarationModifiers.Virtual)).WithBody(SyntaxFactory.Block(body));
    }

    private PropertyDeclarationSyntax CreateBasePropertyStub(SyntaxGenerator gen, IPropertySymbol ps)
    {
        var property = (PropertyDeclarationSyntax)gen.PropertyDeclaration(ps.Name, GetTypeNameSyntax(ps.Type), accessibility: Accessibility.Public, modifiers: DeclarationModifiers.Virtual);
        var accessors = new List<AccessorDeclarationSyntax>();
        if (ps.GetMethod != null) accessors.Add(SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration, SyntaxFactory.Block()));
        if (ps.SetMethod != null) accessors.Add(SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration, SyntaxFactory.Block()));
        return property.WithAccessorList(SyntaxFactory.AccessorList(SyntaxFactory.List(accessors)));
    }

    private SyntaxNode BuildBaseDependenciesInterface(SyntaxGenerator gen, string oldName, List<ISymbol> members)
    {
        var ifaceMembers = members.Select(m =>
        {
            if (m is IMethodSymbol ms && ms.MethodKind != MethodKind.Constructor)
            {
                var parameters = ms.Parameters.Select(p =>
                {
                    var decl = (ParameterSyntax)gen.ParameterDeclaration(p.Name, GetTypeNameSyntax(p.Type));
                    if (p.GetAttributes().Any(a => a.AttributeClass?.Name == "CallerMemberNameAttribute"))
                        decl = gen.AddAttributes(decl, gen.Attribute("CallerMemberName")) as ParameterSyntax ?? decl;
                    if (p.HasExplicitDefaultValue)
                        decl = decl.WithDefault(SyntaxFactory.EqualsValueClause(p.ExplicitDefaultValue == null ? SyntaxFactory.LiteralExpression(SyntaxKind.NullLiteralExpression) : (ExpressionSyntax)gen.LiteralExpression(p.ExplicitDefaultValue)));
                    return decl;
                });
                return gen.MethodDeclaration(ms.Name, parameters: parameters, returnType: GetTypeNameSyntax(ms.ReturnType), accessibility: Accessibility.Public);
            }
            return gen.PropertyDeclaration(m.Name, GetTypeNameSyntax(((IPropertySymbol)m).Type), accessibility: Accessibility.Public);
        });

        return gen.InterfaceDeclaration($"IAuto{oldName}BaseDependencies", accessibility: Accessibility.Public, members: ifaceMembers)
            .WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Comment("/// <summary>Mock this using NSubstitute</summary>")));
    }

    private TypeSyntax GetTypeNameSyntax(ITypeSymbol typeSymbol)
    {
        var syntax = typeSymbol.SpecialType switch
        {
            SpecialType.System_String => SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.StringKeyword)),
            SpecialType.System_Object => SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.ObjectKeyword)),
            SpecialType.System_Void => SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)),
            SpecialType.System_Int32 => SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.IntKeyword)),
            SpecialType.System_Boolean => SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.BoolKeyword)),
            _ => (TypeSyntax)SyntaxFactory.ParseTypeName(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
        };
        return typeSymbol.IsReferenceType && typeSymbol.NullableAnnotation == NullableAnnotation.Annotated ? SyntaxFactory.NullableType(syntax) : syntax;
    }

    private List<ISymbol> ExtractUsedBaseMembers(ClassDeclarationSyntax derivedNode, INamedTypeSymbol targetSymbol, SemanticModel model)
    {
        var baseType = targetSymbol.BaseType;
        if (baseType == null || baseType.SpecialType == SpecialType.System_Object) return new List<ISymbol>();
        var used = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
        foreach (var node in derivedNode.DescendantNodes())
        {
            var symbol = node switch
            {
                InvocationExpressionSyntax i => model.GetSymbolInfo(i.Expression).Symbol,
                MemberAccessExpressionSyntax m => model.GetSymbolInfo(m).Symbol,
                IdentifierNameSyntax id when id.Parent is not MemberAccessExpressionSyntax => model.GetSymbolInfo(id).Symbol,
                _ => null
            };
            if (symbol != null && baseType.GetMembers().Contains(symbol, SymbolEqualityComparer.Default)) used.Add(symbol);
        }
        return used.ToList();
    }

    private SyntaxNode AddMissingUsings(SyntaxNode root, IEnumerable<string> namespaces, SyntaxGenerator gen)
    {
        if (root is not CompilationUnitSyntax cu) return root;
        var current = cu.Usings.Select(u => u.Name?.ToString()).ToHashSet();
        return cu.AddUsings(namespaces.Where(n => !current.Contains(n)).Select(n => (UsingDirectiveSyntax)gen.NamespaceImportDeclaration(n)).ToArray());
    }
}
