namespace FlexibleTesting.Generators;

public static class FlexibleTestingGeneratorCode
{
    public const string GeneratorInstructionsAttributeCode = $$"""
// <auto-generated/>
using System;
using Microsoft.CodeAnalysis;
namespace FlexibleTesting;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class GeneratorInstructionsAttribute : Attribute
{
    public Type[] InterfacesTypes { get; }
    public GeneratorInstructionsAttribute(params Type[] interfacesTypes)
    {
        InterfacesTypes = interfacesTypes;
    }
}
""";

    public const string GeneratorInstructionsInterfaceCode = $$"""
// <auto-generated/>
using System;
namespace FlexibleTesting;

public interface IGeneratorInstructions
{
    void Configure();
}
""";

    public const string OverwritesHelperCode = $$"""
// <auto-generated/>
using System.Linq.Expressions;
namespace FlexibleTesting;

public class Overwrites
{
    public static void ReplaceProperty<TDelegate>(Expression<TDelegate> target, Expression<TDelegate> replacement)
        where TDelegate : Delegate { }

    public static void Replace<TDelegate>(TDelegate target, TDelegate replacement)
        where TDelegate : Delegate { }

    public static void Mockable<TDelegate>(TDelegate value)
        where TDelegate : Delegate { }

    public static void MakePublic<TInterface, TDelegate>(Expression<Func<TInterface, TDelegate>> methodSelector)
        where TDelegate : Delegate { }

    public static void MakePublic<TDelegate>(Expression<Func<TDelegate>> methodSelector)
        where TDelegate : Delegate { }

    public static void Include<T>()
        where T : IGeneratorInstructions { }

    public static void RedirectNew<TTarget, TDelegate>(Func<TTarget> value1, Func<TDelegate> value2)
        where TDelegate : Delegate { }

    public static void Mock<TClass>() { }

    public static void MockWithInterface<TClass, TInterface>() { }

    public static void ForClass<TClass>() { }

    public static void MockInheritance() { }

    public static void InheritFrom<TClass>() { }
}
""";
}
