using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using static FlexibleTesting.AutoImplementGenerator;

namespace FlexibleTesting.Generators;

[Generator]
public class FlexibleTestingGenerator : IIncrementalGenerator
{
    const string GeneratorInstructionsAttributeCode = $$"""
// <auto-generated/>
using System;
using Microsoft.CodeAnalysis;
namespace FlexibleTesting;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false), Embedded]
internal sealed class GeneratorInstructionsAttribute : Attribute
{
    public Type[] InterfacesTypes { get; }
    public GeneratorInstructionsAttribute(params Type[] interfacesTypes)
    {
        InterfacesTypes = interfacesTypes;
    }
}
""";

    const string GeneratorInstructionsInterfaceCode = $$"""
// <auto-generated/>
using System;
namespace FlexibleTesting;

public interface IGeneratorInstructions
{
    void Configure();
}
""";

    const string OverwritesHelperCode = $$"""
// <auto-generated/>
using System.Linq.Expressions;
namespace FlexibleTesting;

public class Overwrites
{
    public static void ReplaceProperty<TDelegate>(Expression<TDelegate> target, Expression<TDelegate> replacement)
        where TDelegate : Delegate { }

    public static void Replace<TDelegate>(TDelegate target, TDelegate replacement)
        where TDelegate : Delegate { }

    public static void Mockable<TDelegate>(TDelegate value)
        where TDelegate : Delegate { }

    public static void MakePublic<TInterface, TDelegate>(Expression<Func<TInterface, TDelegate>> methodSelector)
        where TDelegate : Delegate { }

    public static void MakePublic(string methodName, params Type[] parameterTypes) { }

    public static void Include<T>()
        where T : IGeneratorInstructions { }

    public static void RedirectNew<TTarget, TDelegate>(Func<TTarget> value1, Func<TDelegate> value2)
        where TDelegate : Delegate { }

    public static void Mock<TClass>() { }

    public static void MockWithInterface<TClass, TInterface>() { }

    public static void ForClass<TClass>() { }

    public static void MockInheritance() { }

    public static void InheritFrom<TClass>() { }
}
""";

    private void CreateGeneratorInstructions(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource($"GeneratorInstructionsAttribute.g.cs", GeneratorInstructionsAttributeCode);
            ctx.AddSource($"IGeneratorInstructions.g.cs", GeneratorInstructionsInterfaceCode);
            ctx.AddSource($"Overwrites.g.cs", OverwritesHelperCode);
        });
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // System.Diagnostics.Debugger.Launch();
        CreateGeneratorInstructions(context);

        // 1. Find classes with your specific attribute
        IncrementalValuesProvider<ClassModel> provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "FlexibleTesting.GeneratorInstructionsAttribute",
            predicate: static (node, cancellationToken_) => node is ClassDeclarationSyntax,
            transform: static (ctx, cancellationToken) =>
            {
                ISymbol classSymbol = ctx.TargetSymbol;
                return new ClassModel(classSymbol.Name, classSymbol.ContainingNamespace.ToDisplayString(), GetInterfaceModels(ctx.Attributes[0]));
            }
        );

        context.RegisterSourceOutput(
            provider,
            static (context, classModel) =>
            {
                //throw new System.Exception("Test Laurens, does this even run?" + string.Join(", ",classModel.Interfaces.Select(i => i.FullyQualifiedName)));
                foreach (InterfaceModel interfaceModel in classModel.Interfaces)
                {
                    StringBuilder sourceBuilder = new(
                        $$"""
                        // <auto-generated/>
                        namespace {{classModel.NameSpace}};

                        public partial class {{classModel.Name}}
                        { }
                        
                        """
                    );

                    //Concat class name and interface name to have unique file name if a class implements two interfaces with AutoImplement Attribute
                    string generatedFileName = $"{classModel.Name}_{interfaceModel.FullyQualifiedName}.g.cs";
                    context.AddSource(generatedFileName, sourceBuilder.ToString());
                }
            }
        );
    }

    // ... Methods will be defined below

    public static ImmutableArray<TargetClassData> GetTargetClassesToGenerate(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        return ImmutableArray.Create(new TargetClassData("LegacyCodeProject.Viewmodels", "UserViewModel"));

        // context.TargetNode is the class that has the attribute
        var classDeclaration = (ClassDeclarationSyntax)context.TargetNode;
        var semanticModel = context.SemanticModel;

        // Find the "Configure" method inside this class
        var configureMethod = classDeclaration.Members.OfType<MethodDeclarationSyntax>().FirstOrDefault(m => m.Identifier.Text == "Configure");

        if (configureMethod == null || configureMethod.Body == null)
        {
            return ImmutableArray<TargetClassData>.Empty;
        }

        var results = ImmutableArray.CreateBuilder<TargetClassData>();

        // Look through all method calls (InvocationExpressions) inside the Configure method body
        var invocations = configureMethod.Body.DescendantNodes().OfType<InvocationExpressionSyntax>();

        foreach (var invocation in invocations)
        {
            // We are looking for something that looks like Overwrites.ForClass<T>()
            // This means the expression must be a MemberAccessExpression (e.g., Object.Method)
            if (invocation.Expression is MemberAccessExpressionSyntax memberAccess)
            {
                // Check if the object being called is "Overwrites"
                if (memberAccess.Expression.ToString() == "Overwrites" && memberAccess.Name is GenericNameSyntax genericName && genericName.Identifier.Text == "ForClass")
                {
                    // Get the <T> part (e.g., UserViewModel)
                    var typeArgument = genericName.TypeArgumentList.Arguments.FirstOrDefault();

                    if (typeArgument != null)
                    {
                        // Now we use the SemanticModel.
                        // Syntax just tells us it says "UserViewModel".
                        // SemanticModel tells us EXACTLY what UserViewModel is (its namespace, etc.)
                        var typeInfo = semanticModel.GetTypeInfo(typeArgument, ct);

                        // If the compiler successfully figured out what type T is...
                        if (typeInfo.Type != null && typeInfo.Type.TypeKind != TypeKind.Error)
                        {
                            var typeSymbol = typeInfo.Type;

                            // Extract just the strings we need for code generation!
                            var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : typeSymbol.ContainingNamespace.ToDisplayString();

                            var className = typeSymbol.Name;

                            // Add it to our results
                            results.Add(new TargetClassData(namespaceName, className));
                        }
                    }
                }
            }
        }

        return results.ToImmutable();
    }

    private static void GeneratePartialClass(SourceProductionContext context, TargetClassData targetData)
    {
        // Handle global namespaces gracefully
        string namespaceDeclaration = string.IsNullOrEmpty(targetData.Namespace) ? "" : $"namespace {targetData.Namespace};";

        // Create the source code
        // Note: We use "partial" here so it merges with the original UserViewModel
        string source = $$"""
            // <auto-generated/>
            using System;

            {{namespaceDeclaration}}

            public partial class {{targetData.ClassName}}
            {
                // TODO: Add your generated properties, methods, etc. here
                public void GeneratedMethod() 
                {
                    Console.WriteLine("Hello from generated code inside {{targetData.ClassName}}!");
                }
            }
            """;

        // Add the source file to the compilation
        // We use the class name as the filename (e.g., UserViewModel_Generated.g.cs)
        context.AddSource($"{targetData.ClassName}_Generated.g.cs", source);
    }
}

public record struct TargetClassData(string Namespace, string ClassName);
